<HistoryIndex>:
    BoxLayout:
        id:button_holder
        size_hint_y:None
        height:self.minimum_height
        spacing:20
        pos_hint:{'center_x':.5, 'center_y':.5}
        orientation:'vertical'
    MDIconButton:
        md_bg_color:[1,0,1,.5]
        color:[0,0,0]
        padding:10
        icon:'arrow-left'
        pos_hint:{'right':.2, 'top':.1}
        padding:15
        on_release:app.root.current=app.root.previous()